/* Generated by Cython 0.24 */

#ifndef __PYX_HAVE__glycresoft_sqlalchemy__scoring__offset_frequency__cpeak_relations
#define __PYX_HAVE__glycresoft_sqlalchemy__scoring__offset_frequency__cpeak_relations

struct PeakRelationStruct;
struct PeakRelationStructArray;
struct RelationSpectrumPair;
struct RelationSpectrumPairArray;
struct FittedFeatureStruct;
struct FittedFeatureStructArray;
struct PeakAnnotationStruct;

/* "glycresoft_sqlalchemy/scoring/offset_frequency/cpeak_relations.pxd":24
 * 
 * 
 * cdef public struct PeakRelationStruct:             # <<<<<<<<<<<<<<
 *     PeakStruct from_peak
 *     PeakStruct to_peak
 */
struct PeakRelationStruct {
  struct __pyx_t_21glycresoft_sqlalchemy_5utils_12ccommon_math_PeakStruct from_peak;
  struct __pyx_t_21glycresoft_sqlalchemy_5utils_12ccommon_math_PeakStruct to_peak;
  int from_charge;
  int to_charge;
  int intensity_ratio;
  char *kind;
  struct __pyx_t_21glycresoft_sqlalchemy_5utils_12ccommon_math_MSFeatureStruct *feature;
  int same_terminal;
  struct __pyx_t_21glycresoft_sqlalchemy_5utils_12ccommon_math_MatchedSpectrumStruct *annotation;
};

/* "glycresoft_sqlalchemy/scoring/offset_frequency/cpeak_relations.pxd":36
 * 
 * 
 * cdef public struct PeakRelationStructArray:             # <<<<<<<<<<<<<<
 *     PeakRelationStruct* relations
 *     size_t size
 */
struct PeakRelationStructArray {
  struct PeakRelationStruct *relations;
  size_t size;
};

/* "glycresoft_sqlalchemy/scoring/offset_frequency/cpeak_relations.pxd":41
 * 
 * 
 * cdef public struct RelationSpectrumPair:             # <<<<<<<<<<<<<<
 *     PeakRelationStructArray* relations
 *     MatchedSpectrumStruct* matched_spectrum
 */
struct RelationSpectrumPair {
  struct PeakRelationStructArray *relations;
  struct __pyx_t_21glycresoft_sqlalchemy_5utils_12ccommon_math_MatchedSpectrumStruct *matched_spectrum;
};

/* "glycresoft_sqlalchemy/scoring/offset_frequency/cpeak_relations.pxd":46
 * 
 * 
 * cdef public struct RelationSpectrumPairArray:             # <<<<<<<<<<<<<<
 *     RelationSpectrumPair* pairs
 *     size_t size
 */
struct RelationSpectrumPairArray {
  struct RelationSpectrumPair *pairs;
  size_t size;
};

/* "glycresoft_sqlalchemy/scoring/offset_frequency/cpeak_relations.pxd":51
 * 
 * 
 * cdef public struct FittedFeatureStruct:             # <<<<<<<<<<<<<<
 *     RelationSpectrumPairArray* relation_pairs
 *     MSFeatureStruct* feature
 */
struct FittedFeatureStruct {
  struct RelationSpectrumPairArray *relation_pairs;
  struct __pyx_t_21glycresoft_sqlalchemy_5utils_12ccommon_math_MSFeatureStruct *feature;
  char *kind;
};

/* "glycresoft_sqlalchemy/scoring/offset_frequency/cpeak_relations.pxd":57
 * 
 * 
 * cdef public struct FittedFeatureStructArray:             # <<<<<<<<<<<<<<
 *     FittedFeatureStruct** features
 *     size_t size
 */
struct FittedFeatureStructArray {
  struct FittedFeatureStruct **features;
  size_t size;
};

/* "glycresoft_sqlalchemy/scoring/offset_frequency/cpeak_relations.pxd":62
 * 
 * 
 * cdef public struct PeakAnnotationStruct:             # <<<<<<<<<<<<<<
 *     PeakStruct* peak
 *     PeakRelationStructArray* annotations
 */
struct PeakAnnotationStruct {
  struct __pyx_t_21glycresoft_sqlalchemy_5utils_12ccommon_math_PeakStruct *peak;
  struct PeakRelationStructArray *annotations;
};

#ifndef __PYX_HAVE_API__glycresoft_sqlalchemy__scoring__offset_frequency__cpeak_relations

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

#endif /* !__PYX_HAVE_API__glycresoft_sqlalchemy__scoring__offset_frequency__cpeak_relations */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcpeak_relations(void);
#else
PyMODINIT_FUNC PyInit_cpeak_relations(void);
#endif

#endif /* !__PYX_HAVE__glycresoft_sqlalchemy__scoring__offset_frequency__cpeak_relations */
