package:
    name: glycresoft
    version: 0.5.0

source:
    git_url: "https://github.com/mobiusklein/glycresoft_sqlalchemy.git"

requirements:
    build:
        - python 2.7.*
        - setuptools
        - cython
        - matplotlib
        - numpy
        - scikit-learn
        - pyyaml
        - lxml
        - sqlalchemy
        - pyteomics
        - requests
        - glypy

    run:
        - python 2.7.*
        # - flask
        # - jinja2
        - numpy
        - matplotlib
        - sqlalchemy
        - lxml
        - networkx
        - requests
        - pyyaml
        - scikit-learn
        - pyteomics
        - glypy
test:
    imports:
        - glycresoft_sqlalchemy
    requires:
        - python 2.7.*
