package:
    name: glycresoft
    version: 0.5.0

source:
    git_url: "https://github.com/mobiusklein/glycresoft_sqlalchemy.git"
    git_rev: "master"

build:
    entry_points:
        - "glycresoft-build-database = glycresoft_sqlalchemy.app.build_database:main"
        - "glycresoft-database-search = glycresoft_sqlalchemy.app.run_search:main"
        - "glycresoft-report = glycresoft_sqlalchemy.app.reporting:taskmain"

requirements:
    build:
        - python 2.7.*
        - setuptools
        - cython
        - matplotlib
        - numpy
        - scikit-learn
        - pyyaml
        - lxml
        - sqlalchemy
        - pyteomics
        - requests
        - glypy
        - taxonomylite

    run:
        - python 2.7.*
        # - flask
        # - jinja2
        - numpy
        - matplotlib
        - sqlalchemy
        - lxml
        - networkx
        - requests
        - pyyaml
        - scikit-learn
        - pyteomics
        - glypy
        - taxonomylite
test:
    imports:
        - glycresoft_sqlalchemy
    requires:
        - python 2.7.*
